# Generated by Django 4.0.4 on 2022-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseImg',
            field=models.ImageField(null=True, upload_to='course_img'),
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.TextField(null=True),
        ),
    ]
